-- MySQL Script generated by MySQL Workbench
-- Thu Jun  2 20:40:55 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema runners
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema runners
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `runners` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `runners` ;

-- -----------------------------------------------------
-- Table `runners`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `runners`.`USER` (
  `uid` INT NOT NULL,
  `email` VARCHAR(50) NULL,
  `name` VARCHAR(50) NULL,
  `path_image` VARCHAR(200) NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `UID_UNIQUE` (`uid` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `runners`.`APPS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `runners`.`APPS` (
  `appid` INT NOT NULL,
  `name` VARCHAR(50) NULL,
  `client_id` VARCHAR(50) NULL,
  `client_secret` VARCHAR(50) NULL,
  PRIMARY KEY (`appid`),
  UNIQUE INDEX `appid_UNIQUE` (`appid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `runners`.`INTEGRATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `runners`.`INTEGRATION` (
  `iid` INT NOT NULL,
  `appid` INT NULL,
  `uid` INT NULL,
  `token` VARCHAR(50) NULL,
  PRIMARY KEY (`iid`),
  UNIQUE INDEX `iid_UNIQUE` (`iid` ASC),
  INDEX `fk_appid_idx` (`appid` ASC),
  INDEX `fk_uid_idx` (`uid` ASC),
  CONSTRAINT `fk_appid`
    FOREIGN KEY (`appid`)
    REFERENCES `runners`.`APPS` (`appid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uid`
    FOREIGN KEY (`uid`)
    REFERENCES `runners`.`USER` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `runners`.`ACTIVITIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `runners`.`ACTIVITIES` (
  `aid` INT NOT NULL,
  `iid` INT NULL,
  `type` VARCHAR(50) NULL,
  `distance` VARCHAR(50) NULL,
  `calories` VARCHAR(45) NULL,
  PRIMARY KEY (`aid`),
  UNIQUE INDEX `aid_UNIQUE` (`aid` ASC),
  INDEX `fk_iid_idx` (`iid` ASC),
  CONSTRAINT `fk_iid`
    FOREIGN KEY (`iid`)
    REFERENCES `runners`.`INTEGRATION` (`iid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
